version: '3'

services:
    auth_service:
        build: ./ui
        container_name: nginx_proxy
        environment:
            PORT: 80
            AUTH_SERVER: http://auth_node:8080/api
        #        volumes:
        #            - ./nginx/conf/nginx.conf.template:/etc/nginx/nginx.conf
        #            - ./ui/nginx/mime.types:/etc/nginx/mime.types
        #            - ./ui/nginx/templates:/etc/nginx/templates
        #            - ./srv/dist/static:/home/static/
        ports:
            - "9001:80"
        depends_on:
            - auth_node

    auth_node:
        build: ./srv
        container_name: node_backend
        environment:
            ENV_FILE: dist/envs/.env.development
            PORT: 8080
            DATABASE_TYPE: postgres
            DATABASE_HOST: db
            DATABASE_PORT: 5432
            DATABASE_NAME: myidentity_db
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: root
            DATABASE_SSL: false
        #            STATIC_PATH: "/home/app/dist/static"
        #        entrypoint: ["tail", "-f","/dev/null"]
#        ports:
#            - '8080:8080'
        depends_on:
            - db

    db:
        container_name: myidentity_db
        image: postgres
        restart: always
        volumes:
            - myidentity_db_volume:/var/lib/postgresql/data
#        ports:
#            - 5420:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_DB: myidentity_db
            POSTGRES_PASSWORD: root

#    pgadmin:
#        image: dpage/pgadmin4
#        container_name: pgadmin4_container
#        restart: always
#        ports:
#            - "8888:80"
#        environment:
#            PGADMIN_DEFAULT_EMAIL: postgres@mail.com
#            PGADMIN_DEFAULT_PASSWORD: password@1234

#    mongo:
#        image: mongo
#        restart: always
#        environment:
#            MONGO_INITDB_ROOT_USERNAME: root
#            MONGO_INITDB_ROOT_PASSWORD: example
#        ports:
#            - 27017:27017
#
#    mongo-express:
#        image: mongo-express
#        restart: always
#        ports:
#            - 8081:8081
#        environment:
#            ME_CONFIG_MONGODB_ADMINUSERNAME: root
#            ME_CONFIG_MONGODB_ADMINPASSWORD: example
#            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#            ME_CONFIG_BASICAUTH: false

volumes:
    myidentity_db_volume: