version: '3'
services:
    my_identity:
        build: .
        container_name: my_identity
        links:
            - db
        environment:
            NODE_ENV: dev
            DATABASE_TYPE: postgres
            DATABASE_HOST: db
            DATABASE_PORT: 5432
            DATABASE_NAME: myidentity_db
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: root
            DATABASE_SSL: false
        ports:
            - 9000:9000
        volumes:
            - ./srv/.env.dev:/app/srv/.env.dev
        #            -   ./srv/static:/app/srv/static
        #            -   ./srv/package.json:/app/srv/package.json
        #            -   ./package.json:/app/package.json
        depends_on:
            - db
    db:
        container_name: myidentity_db
        image: postgres
        restart: always
        volumes:
            - myidentity_db_volume:/var/lib/postgresql/data
        ports:
            - 5420:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_DB: myidentity_db
            POSTGRES_PASSWORD: root



volumes:
    myidentity_db_volume:
