version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: reverse_proxy
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/mime.types:/etc/nginx/mime.types
        ports:
            - "80:80"
            - "443:443"

    auth_node:
        build: .
        environment:
            ENV_FILE: dist/envs/.env.aws
            PORT: 8080
        #        entrypoint: ["tail", "-f","/dev/null"]
        ports:
            - '8080:8080'

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
            ME_CONFIG_BASICAUTH: false

