helmBinary: ./helm

repositories:
    -   name: ingress-nginx
        url: https://kubernetes.github.io/ingress-nginx
    -   name: bitnami
        url: https://charts.bitnami.com/bitnami
    -   name: bitnamicharts
        url: oci://registry-1.docker.io/bitnamicharts/postgresql
    -   name: prometheus-community
        url: https://prometheus-community.github.io/helm-charts

releases:
    -   name: postgres
        namespace: postgres
        createNamespace: true
        chart: bitnamicharts/postgresql
        version: ~4.1.0
    -   name: jupyterhub
        namespace: jupyterhub
        createNamespace: true
        chart: bitnami/jupyterhub
        version: ~1.1.12
    -   name: prom-norbac-ubuntu
        namespace: prometheus
        chart: prometheus-community/prometheus
        set:
            -   name: rbac.create
                value: false