backend:
    replicaCount: 1
    image:
        name: localhost/auth-server:latest
        pullPolicy: Never
    service:
        type: ClusterIP
        port: 8080
    readinessProbe:
        path: /api/v1/health-check
    env:
        ENV_FILE: "dist/envs/.env.development"
        PORT: "8080"
        DATABASE_TYPE: "postgres"
        DATABASE_HOST: "postgres-db-postgresql.postgres.svc.cluster.local"
        DATABASE_PORT: "5432"
        DATABASE_NAME: "auth_server_db"
        DATABASE_USERNAME: "auth_server_db_user"
        DATABASE_PASSWORD: "secret"
        DATABASE_SSL: "false"
        MONGO_DATABASE_TYPE: "REAL"
        MONGO_DB_URI: "mongodb://root:secret@mongo-mongodb.mongo.svc.cluster.local:27017/"
    resources:
        requests:
            cpu: "250m"
            memory: "512Mi"
        limits:
            cpu: "500m"
            memory: "1024Mi"


web:
    replicaCount: 1
    image:
        name: localhost/auth-server-ui:latest
        pullPolicy: Never
    service:
        type: ClusterIP
        port: 8080
    env:
        PORT: "8080"
        AUTH_SERVER: "http://auth-server-api.auth-server.svc.cluster.local:8080/api"
    resources:
        requests:
            cpu: "250m"
            memory: "512Mi"
        limits:
            cpu: "500m"
            memory: "1024Mi"

ingress:
    enabled: true
    host: auth.oauth2.local

