replicaCount: 1

image:
  name: sd25/auth-server:latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  path: /api/v1/health-check
  port: 9001

env:
  ENV: "production"
  DATABASE_TYPE: "postgres"
  DATABASE_HOST: "postgres-db-postgresql.postgres.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "auth_server_db"
  DATABASE_USERNAME: "auth_server_db_user"
  DATABASE_PASSWORD: "secret"
  DATABASE_SSL: "false"

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "200m"
    memory: "1Gi"

ingress:
  enabled: false
  className: ""
  host: auth.oauth2.local
  annotations: {}
