backend:
    replicaCount: 1
    image:
        name: docker.io/library/auth-server-srv:latest
        pullPolicy: Never
    service:
        type: ClusterIP
        port: 8080
    readinessProbe:
        path: /api/v1/health-check
    env:
        ENV_FILE: "dist/envs/.env.development"
        PORT: "8080"
        DATABASE_TYPE: "postgres"
        DATABASE_HOST: "postgres-db-postgresql.postgres.svc.cluster.local"
        DATABASE_PORT: "5432"
        DATABASE_NAME: "auth_server_db"
        DATABASE_USERNAME: "auth_server_db_user"
        DATABASE_PASSWORD: "secret"
        DATABASE_SSL: "false"
    resources:
        requests:
            cpu: "50m"
            memory: "512Mi"
        limits:
            cpu: "50m"
            memory: "512Mi"


web:
    replicaCount: 1
    image:
        name: docker.io/library/auth-server-ui:latest
        pullPolicy: Never
    service:
        type: ClusterIP
        port: 8080
    env:
        PORT: "8080"
        AUTH_SERVER: "http://auth-server-api.auth-server.svc.cluster.local:8080/api"
    resources:
        requests:
            cpu: "50m"
            memory: "512Mi"
        limits:
            cpu: "50m"
            memory: "512Mi"

ingress:
    enabled: true
    host: auth.oauth2.local

