apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-server-ui-deployment
spec:
    selector:
        matchLabels:
            app: auth-server-ui
    replicas: {{ .Values.web.replicaCount }}
    template:
        metadata:
            labels:
                app: auth-server-ui
        spec:
            containers:
                -   name: auth-server-ui
                    image: "{{ .Values.web.image.name }}"
                    imagePullPolicy: {{ .Values.web.image.pullPolicy }}
                    ports:
                        -   containerPort: {{ .Values.web.service.port }}
                    env:
                        {{- range $key, $value := .Values.web.env }}
                        -   name: {{ $key }}
                            value: "{{ $value }}"
                        {{- end }}
                    readinessProbe:
                        initialDelaySeconds: 5
                        periodSeconds: 5
                        httpGet:
                            path: /
                            port: {{ .Values.web.service.port }}
                    resources:
                        requests:
                            cpu: {{ .Values.web.resources.requests.cpu }}
                            memory: {{ .Values.web.resources.requests.memory }}
                        limits:
                            cpu: {{ .Values.web.resources.limits.cpu }}
                            memory: {{ .Values.web.resources.limits.memory }}