apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-server
    labels:
        app: auth-server
spec:
    replicas: {{ .Values.backend.replicaCount }}
    selector:
        matchLabels:
            app: auth-server
    template:
        metadata:
            labels:
                app: auth-server
        spec:
            containers:
                -   name: auth-server
                    image: "{{ .Values.backend.image.name }}"
                    imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
                    ports:
                        -   containerPort: {{ .Values.backend.service.port }}
                    env:
                      {{- range $key, $value := .Values.backend.env }}
                        -   name: {{ $key }}
                            value: "{{ $value }}"
                      {{- end }}
                    resources:
                        requests:
                            cpu: {{ .Values.backend.resources.requests.cpu }}
                            memory: {{ .Values.backend.resources.requests.memory }}
                        limits:
                            cpu: {{ .Values.backend.resources.limits.cpu }}
                            memory: {{ .Values.backend.resources.limits.memory }}
                    readinessProbe:
                        initialDelaySeconds: 5
                        periodSeconds: 5
                        httpGet:
                            path: {{ .Values.backend.readinessProbe.path }}
                            port: {{ .Values.backend.service.port }}