apiVersion: v1
kind: Service
metadata:
    name: auth-server-api
spec:
    type: {{ .Values.backend.service.type }}
    selector:
        app: auth-server
    ports:
        -   protocol: "TCP"
            port: {{ .Values.backend.service.port }}
            targetPort: {{ .Values.backend.service.port }}
---
apiVersion: v1
kind: Service
metadata:
    name: auth-server-web
spec:
    type: {{ .Values.web.service.type }}
    selector:
        app: auth-server
    ports:
        -   protocol: "TCP"
            port: {{ .Values.web.service.port }}
            targetPort: {{ .Values.web.service.port }}