name: Build, Test and Release Docker Images as tar

on:
    push:
        branches: [ "main", "development" ]  # Added release branch

jobs:
    build-and-export:
        runs-on: ubuntu-latest

        permissions:
            contents: write  # Needed to upload assets to releases

        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4

            # ---------- Node tests (UI) ----------
            -   name: Set up Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: run srv test
                working-directory: srv
                run: |
                    npm ci
                    npm test

#            -   name: run ui tests
#                working-directory: ui
#                run: |
#                    npm ci
#                    npm test

            # ---------- Docker buildx ----------
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            # ---------- Build docker images ----------
            -   name: Build srv Docker image
                run: |
                    cd srv
                    docker build -t auth-server-srv:latest .

            -   name: Build ui Docker image
                run: |
                    cd ui
                    docker build -t auth-server-ui:latest .
