name: Build and Create Docker Image

on:
    push:
        branches: [ "main", "development" ]  # Added release branch

jobs:
    build-and-export:
        runs-on: ubuntu-latest

        permissions:
            contents: write  # Needed to upload assets to releases

        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4

            # ---------- Docker buildx ----------
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            # ---------- Build docker images ----------
            -   name: Build srv Docker image
                run: |
                    cd srv
                    docker build -t auth-server-srv:latest .

            -   name: Build ui Docker image
                run: |
                    cd ui
                    docker build -t auth-server-ui:latest .
