name: Build and Release Docker Images as tar

on:
    push:
        branches: [ "main", "development" ]  # Added release branch

jobs:
    build-and-export:
        runs-on: ubuntu-latest

        permissions:
            contents: write  # Needed to upload assets to releases

        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Build srv Docker image
                run: |
                    cd srv
                    docker build -t auth-server-srv:latest .

            -   name: Build ui Docker image
                run: |
                    cd ui
                    docker build -t auth-server-ui:latest .

            -   name: Export srv image to tar
                if: github.ref == 'refs/heads/release'
                run: |
                    docker save -o srv-image.tar auth-server-srv:latest

            -   name: Export ui image to tar
                if: github.ref == 'refs/heads/release'
                run: |
                    docker save -o ui-image.tar auth-server-ui:latest
