name: Build, Test and Create Docker Image

on:
    push:
        branches: [ "main", "development" ]  # Added release branch

jobs:
    build-and-export:
        runs-on: ubuntu-latest

        permissions:
            contents: write  # Needed to upload assets to releases

        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4

            # ---------- Docker buildx ----------
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Install dependencies and run Karma tests (ui)
                working-directory: ui
                run: |
                    npm ci            # Install exact dependencies based on package-lock.json
                    npm run test -- --watch=false --browsers=ChromeHeadless

            # ---------- Build docker images ----------
            -   name: Build srv Docker image
                run: |
                    cd srv
                    docker build -t auth-server-srv:latest .

            -   name: Build ui Docker image
                run: |
                    cd ui
                    docker build -t auth-server-ui:latest .
