name: Build, Test and Create Docker Image

on:
    push:
        branches: [ "main", "development", "release" ]  # Added release branch

jobs:
    build-and-export:
        runs-on: ubuntu-latest

        permissions:
            contents: write  # Needed to upload assets to releases

        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4

            # ---------- Docker buildx ----------
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Run Srv Test
                working-directory: srv
                run: |
                    npm ci            # Install exact dependencies based on package-lock.json
                    npm run release

            -   name: Run UI Test
                working-directory: ui
                run: |
                    npm ci            # Install exact dependencies based on package-lock.json
                    npm run test -- --watch=false --browsers=ChromeHeadless
                    npm run e2e:test
                    
                    

